const app=document.querySelector('#app');
const profiles={
 progress:{emoji:'📈',name:'The Progress Chaser',subtitle:'You come alive when you can see the climb.',text:'A visible win, a level-up, or a clear “before and after” seems to switch your engine on. You are not shallow for liking proof: noticing progress can make effort feel meaningful.',try:'Give one goal a scoreboard that feels friendly — streaks, chapters finished, weights lifted, or a simple “better than last week?” check-in.'},
 purpose:{emoji:'🌍',name:'The Purpose Seeker',subtitle:'Meaning is your most renewable fuel.',text:'You are energised when an effort connects to something bigger than a checkbox: people you care about, a value, a craft, or a future you want to help build.',try:'Write one sentence that links a current task to something you genuinely care about. Keep it visible where the task happens.'},
 freedom:{emoji:'🗺️',name:'The Freedom Lover',subtitle:'Choice keeps your spark from feeling like a chore.',text:'You are more likely to show up when there is room to choose the route, the timing, or the version. A plan can help — as long as it still leaves you some steering wheel.',try:'Create a menu of three acceptable ways to move one goal forward. Pick the version that fits today.'},
 social:{emoji:'🤝',name:'The Social Energiser',subtitle:'Good company turns effort into an event.',text:'Connection gives your motivation a lift. Encouragement, collaboration, or simply being around people with a shared aim can make a task feel warmer and more doable.',try:'Make one goal social this week: invite a friend, join a class, or send a small progress note to someone who roots for you.'},
 challenge:{emoji:'🏔️',name:'The Challenge Hunter',subtitle:'A worthy stretch wakes you up.',text:'You appear to enjoy a goal with some edge to it. Difficulty can make the experience more interesting, especially when you can test your skill and feel yourself growing.',try:'Choose a stretch goal with a clear “easy exit”: make it hard enough to be interesting, but small enough to attempt today.'},
 comfort:{emoji:'☕',name:'The Comfort Curator',subtitle:'The experience matters as much as the outcome.',text:'You are drawn to goals that feel good while you do them: calm, cosy, playful, beautiful, or satisfying. That is not a lack of discipline; immediate enjoyment can help repetition.',try:'Add one pleasant cue to a useful task — music, a better setting, a warm drink, or a tiny end-of-task ritual.'}
};
const questions=[
 ['You have a free evening. Which invitation has the strongest pull?',[['progress','A workshop where I leave noticeably better at something'],['purpose','Helping with something that matters to me'],['freedom','An open-ended adventure with no rigid plan'],['social','A lively plan with favourite people'],['challenge','Trying something I might be terrible at (at first)'],['comfort','A cosy ritual that makes the evening feel lovely']]],
 ['A new project lands on your desk. Your first thought is…',[['progress','“How will I know I am getting somewhere?”'],['purpose','“Why does this matter — and to whom?”'],['freedom','“How much room do I have to make this my way?”'],['social','“Who would make this more fun or easier?”'],['challenge','“What is the interesting hard part?”'],['comfort','“How can I make the process less grim?”']]],
 ['Which mini-victory would make you oddly proud?',[['progress','A chart that shows I kept improving'],['purpose','Knowing my effort genuinely helped someone'],['freedom','Finding my own clever way through'],['social','A teammate saying “we did it”'],['challenge','Doing the thing I once thought was beyond me'],['comfort','Turning a dreaded routine into a nice moment']]],
 ['Your motivation is fading. What is most likely to revive it?',[['progress','A measurable milestone just ahead'],['purpose','Remembering the reason I started'],['freedom','Permission to change the plan'],['social','A friendly nudge or shared session'],['challenge','A bolder goal to aim at'],['comfort','Making the next step more pleasant']]],
 ['Pick a fictional quest companion.',[['progress','The one with a map, metrics, and “level up” badges'],['purpose','The one protecting a cause bigger than themselves'],['freedom','The improviser who refuses the obvious route'],['social','The morale booster who gathers the crew'],['challenge','The brave one who volunteers for the scary bit'],['comfort','The one who packed snacks, blankets, and a playlist']]],
 ['What makes a routine worth repeating?',[['progress','It lets me see skills or results accumulate'],['purpose','It reflects the person I want to be'],['freedom','I can adapt it when life changes'],['social','It gives me a moment of connection'],['challenge','It keeps stretching me a little'],['comfort','I actually enjoy how it feels']]],
 ['Choose a message to receive at 8 a.m.',[['progress','“Tiny gains count. What is today’s one?”'],['purpose','“Your actions can stand for something.”'],['freedom','“Choose the version that fits today.”'],['social','“Someone is cheering for you.”'],['challenge','“Do one thing your future self finds impressive.”'],['comfort','“Make today a little nicer while you are at it.”']]],
 ['When do you feel most “in the zone”?',[['progress','When feedback tells me I am improving'],['purpose','When the work feels meaningful'],['freedom','When I can explore without being micromanaged'],['social','When I am building something alongside others'],['challenge','When I am fully absorbed in a demanding problem'],['comfort','When the setting and rhythm feel just right']]],
 ['A goal goes off track. Your instinct is to…',[['progress','Find a smaller metric and rebuild momentum'],['purpose','Reconnect with the reason it mattered'],['freedom','Redesign it so it fits real life'],['social','Talk it through with someone supportive'],['challenge','Treat the setback as a puzzle to beat'],['comfort','Lower the friction and make restarting gentler']]],
 ['Your ideal reward for a month of effort?',[['progress','Seeing unmistakable evidence that I grew'],['purpose','Knowing it made a positive difference'],['freedom','Having more options and confidence to choose'],['social','Celebrating with people who shared the ride'],['challenge','A new, harder mountain to climb'],['comfort','A deeply enjoyable day with no guilt attached']]]
];
let page=0,answers=[];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function intro(){app.innerHTML=`<section class="hero"><div class="eyebrow">A playful reflection · 3 minutes</div><h1>What’s your motivation style?</h1><p>Ten curious choices. One shareable result. Discover what tends to put wind in your sails — from visible progress to a good challenge, meaningful work, freedom, people, or a dash of delight.</p><p class="tag">Private: answers stay in this browser</p><br><button class="start">Find my spark →</button></section>`;app.querySelector('button').onclick=render;}
function render(){const [title,choices]=questions[page];app.innerHTML=`<div class="eyebrow">Question ${page+1} of ${questions.length}</div><div class="progress"><span style="width:${page/questions.length*100}%"></span></div><section class="question"><h2>${esc(title)}</h2><div class="choices">${choices.map(([id,text])=>`<button class="choice ${answers[page]===id?'selected':''}" data-id="${id}">${esc(text)}</button>`).join('')}</div><div class="actions"><button class="secondary" id="back" ${page?'':'disabled'}>Back</button><button id="next" ${answers[page]?'':'disabled'}>${page===questions.length-1?'Reveal my style ✨':'Next →'}</button></div></section>`;app.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{answers[page]=b.dataset.id;render()});app.querySelector('#back').onclick=()=>{page--;render()};app.querySelector('#next').onclick=()=>page===questions.length-1?result():(page++,render());}
function copyText(text){const area=document.createElement('textarea');area.value=text;area.setAttribute('readonly','');area.style.cssText='position:fixed;opacity:0;pointer-events:none';document.body.append(area);area.select();const copied=document.execCommand('copy');area.remove();return copied;}
function result(){const totals=Object.fromEntries(Object.keys(profiles).map(k=>[k,0]));answers.forEach(a=>totals[a]++);const ranked=Object.entries(totals).sort((a,b)=>b[1]-a[1]);const p=profiles[ranked[0][0]], second=profiles[ranked[1][0]];app.innerHTML=`<section class="result"><div class="emoji">${p.emoji}</div><div class="eyebrow">Your motivation style</div><h1>${p.name}</h1><p class="subtitle">${p.subtitle}</p><p>${p.text}</p><section class="card"><span class="eyebrow">Your next spark</span><h2>${p.try}</h2><p>You also showed a dash of <strong>${esc(second.name.replace('The ',''))}</strong> energy. Motivation can change with the goal and the day — this is a conversation starter, not a fixed label.</p></section><button class="share" id="share">Copy my result to share</button><button class="secondary" id="again">Try again</button><div class="why"><h2>Why this is research-informed</h2><p>This original quiz is inspired by Self-Determination Theory: autonomy, competence, and relatedness are broadly associated with more self-determined motivation. Enjoyment and personally valued reasons also matter. The six playful styles and their scoring are Calcora’s design, not a validated psychological measure.</p><details><summary>References &amp; limits</summary>${references()}</details></div></section>`;app.querySelector('#again').onclick=()=>{page=0;answers=[];render()};app.querySelector('#share').onclick=()=>{const text=`I’m ${p.name} on Calcora’s Motivation Style quiz. What puts wind in your sails? ${location.href}`;const button=app.querySelector('#share');button.textContent=copyText(text)?'Copied — paste it anywhere ✨':'Select and copy your result instead';};window.scrollTo(0,0)}
function references(){return `<ol class="ref"><li><a href="https://doi.org/10.1037/0003-066X.55.1.68" target="_blank" rel="noopener">Ryan, R. M., & Deci, E. L. (2000). Self-determination theory and the facilitation of intrinsic motivation, social development, and well-being. American Psychologist, 55(1), 68–78.</a> Explains autonomy, competence, and relatedness as basic psychological needs.</li><li><a href="https://doi.org/10.1037/a0035661" target="_blank" rel="noopener">Cerasoli, C. P., Nicklin, J. M., & Ford, M. T. (2014). Intrinsic motivation and extrinsic incentives jointly predict performance: A 40-year meta-analysis. Psychological Bulletin, 140(4), 980–1008.</a> Finds that intrinsic motivation and incentives can both relate to performance, depending on context.</li><li><a href="https://doi.org/10.1002/ejsp.674" target="_blank" rel="noopener">Lally, P., et al. (2010). How are habits formed: Modelling habit formation in the real world. European Journal of Social Psychology, 40(6), 998–1009.</a> Examines repetition in stable contexts and automaticity.</li></ol><p class="ref">Sources support broad motivational principles, not individual results, the six labels, or the scoring rule. This quiz does not diagnose motivation, predict performance, or measure personality.</p>`}
document.querySelector('#methodContent').innerHTML=`<h2>Method &amp; references</h2>${references()}`;document.querySelector('#method').onclick=()=>document.querySelector('#methodDialog').showModal();document.querySelector('#closeMethod').onclick=()=>document.querySelector('#methodDialog').close();intro();
